### ISSUE TITLE
Finish recoding data file

### ISSUE THREAD

**Issue by ghaudek** [Suited-IOP/Assessment-Science-Analyst#12]

**Comment by ghaudek** [comment]
@MenuchaDSperlin When I did the data set for comparison, I didn't do the recoding of performance and demographics.  Can you please do that in the new file, and then let's decide which syntax, output, and data files we'll continue to work with.

**Comment by MenuchaDSperlin** [comment]
Sweet, you got it!

Would love to talk tomorrow about the stuff you pulled cuz it looked all the reliabilities improved, an if it did- what does that look like for the future of the IB assessment (with Regions coming on too). How does that change predictions?

**Comment by ghaudek** [comment]
Can do!  I did add a list of what I think are the rank order competencies to continue to work through in the other ticket, so please feel free to add any of your thoughts to that!

**Comment by MenuchaDSperlin** [comment]
All recoding, syntax and dataset updated. 
Just need to discuss which one we use for the main and then I'll close this issue.
