### ISSUE TITLE
Document analyses

### ISSUE THREAD

**Issue by ghaudek** [Suited-IOP/Assessment-Science-Analyst#15]

**Comment by MenuchaDSperlin** [comment]
https://docs.google.com/document/d/1D7AJYIVwDQnRlFcMdnPCvJX7y1i2poRVmrMVmjh5O8Y/edit

High level to get your reactions @ghaudek. Wondering how much more detail we want in here?

**Comment by ghaudek** [comment]
Looks good as a start!  Here's the level of detail I think should be in here:
If we came back to this document in a year, would we be able to get enough context about what was done and find the data/syntax/results so that we could come to the same conclusions/explain what we did to someone else/repeat the same analyses?

**Comment by ghaudek** [comment]
@MenuchaDSperlin once you think you've got this written up, let's have Amer review it to see if we've included enough detail for him to understand what we did...that might be a really good test of whether it's ready to put on the shelf yet!
