### ISSUE TITLE
Brainstorming & prioritizing concepts to test

### ISSUE THREAD

**Issue by ghaudek** [Suited-IOP/Assessment-Science-Analyst#18]
**Cognitive Ability and Personality Trait Correlates**
Shorter list of specific cognitive skills that we want to measure in the PA 

- [ ] Greg
- [ ] Amer
- [ ] Menucha

**H-H**
How to measure these facets with less obvious “right answers”

- [ ] Greg
- [ ] Amer
- [x] Menucha

**Comment by MenuchaDSperlin** [comment]
- [ ] Research ECA and Personality correlations

**Comment by MenuchaDSperlin** [comment]
Here's a doc I started summarizing what I thought were helpful and key points

https://docs.google.com/document/d/1AK7gOAg9WVoEu6qtCcxzQz5Wr2WNQeJqqePYLJMp3f8/edit

**Comment by ghaudek** [comment]
Summary/highlights from a few articles on personality correlates with CA:
https://docs.google.com/document/d/1a699zGRy_O9uak-TIQ4f7d5ORfChKnSyRxyYscGEjoo/edit?usp=sharing

**Comment by AmerOdehIO** [comment]
Summary of my notes:
https://docs.google.com/document/d/1E0-Qf7FHoFg85AcF9yTYZe7sSZ1JFvenG-_iIFx2z5M/edit?usp=sharing

**Comment by MenuchaDSperlin** [comment]
@AmerOdehIO  do you mind pulling these articles for me, please?

https://docs.google.com/document/d/1chlUAPvq2HxLlrr7hu9SqJBGAjOMXfITw_LBMdQabPI/edit#

**Comment by MenuchaDSperlin** [comment]
H-H Rewrite https://docs.google.com/spreadsheets/d/1Pmm85hnBfp0z4i1ZxRLZDiqe5cSplSkMUDNfVniiuIU/edit
