### ISSUE TITLE
Add Research Ideas to the doc

### ISSUE THREAD

**Issue by MenuchaDSperlin** [Suited-IOP/Assessment-Science-Analyst#22]

**Comment by ghaudek** [comment]
Here's the doc from the epic: 
https://docs.google.com/document/d/1xyoMj-pE7IXcl5JrcmY7WDjkQ_1VtbA3DXo4b4UzHd0/edit

**Comment by ghaudek** [comment]
Check when you're done!

- [ ] Amer
- [ ] Menucha
- [ ] Greg

**Comment by ghaudek** [comment]
Finish review and update of list by 12/10
